<a href="https://colab.research.google.com/github/diksharai9/Alien-Hunt/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [20]:
a=np.array([1,2,3],dtype='int16')
print(a)


[1 2 3]


In [10]:
b=np.array([[1,2,3],[2,3,4],[4,5,6]])
print(b)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [16]:
# Get dimension of the array
a.ndim
# b.ndim

2

In [17]:
# Get the shape-> number of rows and cols
# a.shape
b.shape

(3, 3)

In [21]:
#Get the numpy array datatype
a.dtype
# b.dtype
# we can change the datatype if we want by specifying a parametere in np.array such as dtype='int16'

dtype('int16')

### **Accessing specific elements of the numpy array**





In [22]:
# get a specific element a[r,c]
b[1,2]

4

In [23]:
# to get the complete row we can use the colon
b[1,:]

array([2, 3, 4])

In [27]:
# get specific elements of the cell in a fancy way[startIndex:end:stepSize]
b[1,0:2:1]

array([2, 3])

### **Initializing the arrays**

In [29]:
# All the matrix np.zeros((r,c,c,c),dtype='')
np.zeros((2,1))

array([[0.],
       [0.]])

In [30]:
# Initializing all with ones
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [31]:
# Initializing all the array the same but anyother number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [32]:
# Initializing the array like already used array with a different number but with same dimensions
np.full_like(a,3)

array([3, 3, 3], dtype=int16)

In [34]:
# Initializing array with random numbers
np.random.rand(4,2)


array([[0.15892762, 0.20464762],
       [0.30119269, 0.22179492],
       [0.44114847, 0.73435232],
       [0.61679981, 0.50621251]])

### **Copying Arrays**

In [36]:
# it will not create a copy rather will point to the same object as a
c=a
print(c)
c[0]=5
print(a)

[1 2 3]
[5 2 3]


In [37]:
# if we want to assign a copy
c=a.copy()
print(c)

[5 2 3]


### **Mathematics**

In [38]:
print(a)

[5 2 3]


In [48]:
a+2
# similarly we can all the arithematic ops element wise  

array([27,  6, 11], dtype=int16)

In [49]:
np.cos(a)

array([ 0.99120283, -0.6536436 , -0.91113025], dtype=float32)

### **Linear Algebra**

In [50]:
# we can multiply two matrices
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [52]:
# finding the determinant of the matrix
c=np.identity(3)
np.linalg.det(c)

1.0

### **Statistics**

In [53]:
stats=np.array([[1,2,3],[2,3,4]])
stats

array([[1, 2, 3],
       [2, 3, 4]])

In [54]:
np.min(stats)
# np.min(stats,axis=1)-> to get the min from first row


1

In [55]:
np.max(stats)

4

### **Miscellaneous**

In [ ]:
filedata=np.getfromtxt('filename.extension',delimiter=',')
filedata.astype('int32')

In [ ]:
filedata>50
filedata[filedata>50]

In [56]:
a=np.array([1,2,3,4,56])
a[[1,2,3]]



array([2, 3, 4])